/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bojan_strbac_chataplication_Crypto */

#ifndef _Included_bojan_strbac_chataplication_Crypto
#define _Included_bojan_strbac_chataplication_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bojan_strbac_chataplication_Crypto
 * Method:    crypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bojan_strbac_chataplication_Crypto_crypt (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
